"""Initial database schema with user management

Revision ID: e58f0edf34f6
Revises: 
Create Date: 2026-01-06 13:04:16.959168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e58f0edf34f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('judge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=30), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('court', sa.String(length=150), nullable=False),
    sa.Column('city', sa.String(length=30), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('is_federal', sa.Boolean(), nullable=True),
    sa.Column('is_retired', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('first_name', 'last_name', 'court', name='unique_judge')
    )
    with op.batch_alter_table('judge', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_judge_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_judge_court'), ['court'], unique=False)
        batch_op.create_index(batch_op.f('ix_judge_is_federal'), ['is_federal'], unique=False)
        batch_op.create_index(batch_op.f('ix_judge_is_retired'), ['is_retired'], unique=False)
        batch_op.create_index(batch_op.f('ix_judge_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_judge_state'), ['state'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('ban_reason', sa.Text(), nullable=True),
    sa.Column('banned_at', sa.DateTime(), nullable=True),
    sa.Column('banned_by_id', sa.Integer(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['banned_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_is_banned'), ['is_banned'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('banned_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ban_reason', sa.Text(), nullable=False),
    sa.Column('banned_by_id', sa.Integer(), nullable=False),
    sa.Column('banned_at', sa.DateTime(), nullable=False),
    sa.Column('is_unbanned', sa.Boolean(), nullable=False),
    sa.Column('unbanned_at', sa.DateTime(), nullable=True),
    sa.Column('unban_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['banned_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('banned_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_banned_user_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_banned_user_is_unbanned'), ['is_unbanned'], unique=False)
        batch_op.create_index(batch_op.f('ix_banned_user_username'), ['username'], unique=False)

    op.create_table('media_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('judge_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('headline', sa.String(length=500), nullable=False),
    sa.Column('news_source', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['judge_id'], ['judge.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('judge_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('fairness_concern', sa.Boolean(), nullable=True),
    sa.Column('bias_concern', sa.Boolean(), nullable=True),
    sa.Column('temperament_concern', sa.Boolean(), nullable=True),
    sa.Column('review_text', sa.Text(), nullable=False),
    sa.Column('court_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['judge_id'], ['judge.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('target_review_id', sa.Integer(), nullable=True),
    sa.Column('target_media_link_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['target_media_link_id'], ['media_link.id'], ),
    sa.ForeignKeyConstraint(['target_review_id'], ['review.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_log_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_log_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_admin_log_action_type'))

    op.drop_table('admin_log')
    op.drop_table('review')
    op.drop_table('media_link')
    with op.batch_alter_table('banned_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_banned_user_username'))
        batch_op.drop_index(batch_op.f('ix_banned_user_is_unbanned'))
        batch_op.drop_index(batch_op.f('ix_banned_user_email'))

    op.drop_table('banned_user')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_is_banned'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('judge', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_judge_state'))
        batch_op.drop_index(batch_op.f('ix_judge_last_name'))
        batch_op.drop_index(batch_op.f('ix_judge_is_retired'))
        batch_op.drop_index(batch_op.f('ix_judge_is_federal'))
        batch_op.drop_index(batch_op.f('ix_judge_court'))
        batch_op.drop_index(batch_op.f('ix_judge_city'))

    op.drop_table('judge')
    # ### end Alembic commands ###
