"""Add content flagging system

Revision ID: f15828479bb1
Revises: e58f0edf34f6
Create Date: 2026-01-08 11:17:45.814941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f15828479bb1'
down_revision = 'e58f0edf34f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=True),
    sa.Column('media_link_id', sa.Integer(), nullable=True),
    sa.Column('flag_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_by_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_action', sa.String(length=50), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['media_link_id'], ['media_link.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['review_id'], ['review.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_flags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_flags_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_flags_is_resolved'), ['is_resolved'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_flags_media_link_id'), ['media_link_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_flags_review_id'), ['review_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_content_flags_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('content_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_flags_user_id'))
        batch_op.drop_index(batch_op.f('ix_content_flags_review_id'))
        batch_op.drop_index(batch_op.f('ix_content_flags_media_link_id'))
        batch_op.drop_index(batch_op.f('ix_content_flags_is_resolved'))
        batch_op.drop_index(batch_op.f('ix_content_flags_created_at'))

    op.drop_table('content_flags')
    # ### end Alembic commands ###
